import numpy as np, MNN
D = r'E:/AndroidStudioProjects/qwen3tts-mnn/artifacts/device-smoke'
emb = np.fromfile(D + '/gb_emb_f32.raw', dtype=np.float32).reshape(1,1,2048)
pos = np.fromfile(D + '/gb_pos_f32.raw', dtype=np.float32).reshape(3,1,1)
kvk = np.fromfile(D + '/gb_kvk_f32.raw', dtype=np.float32).reshape(28,1,8,35,128)
kvv = np.fromfile(D + '/gb_kvv_f32.raw', dtype=np.float32).reshape(28,1,8,35,128)
cp = np.fromfile(D + '/gb_cp_i32.raw', dtype=np.int32).reshape(1)
interp = MNN.Interpreter(D + '/graphb_static_t35_fp16.mnn')
interp.setExternalFile(D + '/graphb_static_t35_fp16.mnn.weight')
s2 = interp.createSession()
interp.resizeTensor(interp.getSessionInput(s2,'inputs_embeds'), (1,1,2048))
interp.resizeTensor(interp.getSessionInput(s2,'position_ids'), (3,1,1))
interp.resizeTensor(interp.getSessionInput(s2,'kv_k'), (28,1,8,35,128))
interp.resizeTensor(interp.getSessionInput(s2,'kv_v'), (28,1,8,35,128))
interp.resizeTensor(interp.getSessionInput(s2,'cache_position'), (1,))
interp.resizeSession(s2)
def feed(name, arr, dt):
    t = interp.getSessionInput(s2, name)
    ht = MNN.Tensor(tuple(arr.shape), dt, arr.ravel(), MNN.Tensor_DimensionType_Caffe)
    t.copyFromHostTensor(ht)
feed('inputs_embeds', emb, MNN.Halide_Type_Float)
feed('position_ids', pos, MNN.Halide_Type_Float)
feed('kv_k', kvk, MNN.Halide_Type_Float)
feed('kv_v', kvv, MNN.Halide_Type_Float)
feed('cache_position', cp, MNN.Halide_Type_Int)
ot = interp.getSessionOutput(s2, 'hidden_states')
interp.runSession(s2)
osh = [d if d > 0 else 2048 for d in ot.getShape()]
ho = MNN.Tensor(osh, MNN.Halide_Type_Float, MNN.Tensor_DimensionType_Caffe)
ot.copyToHostTensor(ho)
mnn_h = np.asarray(ho.getNumpyData()).reshape(osh).astype(np.float32)
mnn_h.tofile(D + '/gb_out_pc_mnn_f32.raw')
ref = np.load(D + '/gb_ref_hidden_fp32.npy').ravel()
a = mnn_h.ravel().astype(np.float64); b = ref.astype(np.float64)
c = float(np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)+1e-9))
print('PC-MNN-fp16 vs ORT-ref:', round(c,6), 'maxabs', float(np.abs(mnn_h).max()))