import numpy as np, MNN, torch, time
ART = r'E:/AndroidStudioProjects/qwen3tts-mnn/artifacts/m2'
g = torch.load(ART + '/golden_io.pt', map_location='cpu')
codes = g['codes'].numpy().astype(np.int32)
wav_ref = g['wav'].numpy()
interp = MNN.Interpreter(ART + '/tokenizer_decoder_nonan.mnn')
sess = interp.createSession()
it = interp.getSessionInput(sess, 'codes')
interp.resizeTensor(it, (1,16,300))
interp.resizeSession(sess)
ht = MNN.Tensor((1,16,300), MNN.Halide_Type_Int, codes.ravel(), MNN.Tensor_DimensionType_Caffe)
it.copyFromHostTensor(ht)
ot = interp.getSessionOutput(sess, 'waveform')
t0 = time.time()
interp.runSession(sess)
t1 = time.time()
oshape = list(ot.getShape())
print('output shape:', oshape, flush=True)
if oshape[2] <= 0: oshape[2] = 576000
ho = MNN.Tensor(oshape, MNN.Halide_Type_Float, MNN.Tensor_DimensionType_Caffe)
ot.copyToHostTensor(ho)
wav = np.asarray(ho.getNumpyData()).reshape(oshape)
print('mnn elapsed(s):', round(t1-t0,3), 'wav', wav.shape, flush=True)
a = wav_ref.astype(np.float64).ravel(); b = wav.astype(np.float64).ravel()
n = min(len(a), len(b)); a=a[:n]; b=b[:n]
cos = float(np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)+1e-9))
mae = float(np.mean(np.abs(a-b))); mx = float(np.max(np.abs(a-b)))
si = 10*np.log10(np.sum(a**2)/(np.sum((a-b)**2)+1e-9))
print('MNN vs PyTorch: cosine', round(cos,6), 'mae', round(mae,8), 'maxabs', round(mx,6), 'SI-SDR(dB)', round(float(si),3), flush=True)
print('M3_DONE', flush=True)