import numpy as np, MNN, MNN.expr as expr, time
D = r'E:/AndroidStudioProjects/qwen3tts-mnn/artifacts/device-smoke'
emb = np.fromfile(D + '/gb_emb_f32.raw', dtype=np.float32).reshape(1,1,2048)
pos = np.fromfile(D + '/gb_pos_f32.raw', dtype=np.float32).reshape(3,1,1)
kvk = np.fromfile(D + '/gb_kvk_f32.raw', dtype=np.float32).reshape(28,1,8,35,128)
kvv = np.fromfile(D + '/gb_kvv_f32.raw', dtype=np.float32).reshape(28,1,8,35,128)
cp = np.fromfile(D + '/gb_cp_i32.raw', dtype=np.int32).reshape(1)
interp = MNN.Interpreter(D + '/graphb_static_t35_fp16.mnn')
interp.setExternalFile(D + '/graphb_static_t35_fp16.mnn.weight')
sess = interp.createSession()
ins = interp.getSessionInputAll(sess)
outs = interp.getSessionOutputAll(sess)
print('model input names:', list(ins.keys()))
mod = MNN.nn.load_module(list(ins.keys()), list(outs.keys()), interp, None)
print('module loaded')
def mkvar(name, arr, dt):
    v = expr._Input(tuple(arr.shape), MNN.Tensor_DimensionType_Caffe, dt)
    expr.assign(v, expr.const(arr.ravel().tolist(), tuple(arr.shape), dt))
    return v
vv_in = mkvar('inputs_embeds', emb, MNN.Halide_Type_Float)
vv_pos = mkvar('position_ids', pos, MNN.Halide_Type_Float)
vv_k = mkvar('kv_k', kvk, MNN.Halide_Type_Float)
vv_v = mkvar('kv_v', kvv, MNN.Halide_Type_Float)
vv_cp = mkvar('cache_position', cp, MNN.Halide_Type_Int)
t0 = time.time()
res = mod.onForward([vv_in, vv_pos, vv_k, vv_v, vv_cp])
t1 = time.time()
out = res[0].read()
mh = np.asarray(out).reshape(-1).astype(np.float32)
print('Module elapsed:', round(t1-t0,2), 'elems', mh.size, 'maxabs', float(np.abs(mh).max()), flush=True)
ref = np.load(D + '/gb_ref_hidden_fp32.npy').ravel()
n = min(len(mh), len(ref)); a = mh[:n].astype(np.float64); b = ref[:n].astype(np.float64)
c = float(np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)+1e-9))
print('PC-Module vs ORT-ref: cosine', round(c,6), flush=True)