import numpy as np, onnxruntime as ort, MNN, time
D = r'E:/AndroidStudioProjects/qwen3tts-mnn/artifacts/device-smoke'
np.random.seed(11)
B,H,T,Dd,Cd = 1, 8, 35, 128, 2048
emb = np.random.randn(1,1,Cd).astype(np.float32)
pos = np.zeros((3,1,1), dtype=np.float32)
pos[0,0,0]=34; pos[1,0,0]=34; pos[2,0,0]=34
kvk = (np.random.randn(28,B,H,T,Dd)*0.05).astype(np.float32)
kvv = (np.random.randn(28,B,H,T,Dd)*0.05).astype(np.float32)
cp64 = np.array([34], dtype=np.int64)
cp32 = cp64.astype(np.int32)
sess = ort.InferenceSession(D + '/graphb_static_t35_nonan.onnx', providers=['CPUExecutionProvider'])
t0=time.time()
ref_hidden, ref_layer = sess.run(None, {'inputs_embeds': emb, 'position_ids': pos, 'kv_k': kvk, 'kv_v': kvv, 'cache_position': cp64})
t1=time.time()
print('ORT fp32:', round(t1-t0,2), 's, finite', bool(np.isfinite(ref_hidden).all()), flush=True)
interp = MNN.Interpreter(D + '/graphb_static_t35_fp16.mnn')
s2 = interp.createSession()
def feed(name, arr, dt):
    t = interp.getSessionInput(s2, name)
    ht = MNN.Tensor(tuple(arr.shape), dt, arr.ravel(), MNN.Tensor_DimensionType_Caffe)
    t.copyFromHostTensor(ht)
feed('inputs_embeds', emb, MNN.Halide_Type_Float)
feed('position_ids', pos, MNN.Halide_Type_Float)
feed('kv_k', kvk, MNN.Halide_Type_Float)
feed('kv_v', kvv, MNN.Halide_Type_Float)
feed('cache_position', cp32, MNN.Halide_Type_Int)
ot = interp.getSessionOutput(s2, 'hidden_states')
t2=time.time()
interp.runSession(s2)
t3=time.time()
osh = list(ot.getShape())
osh = [d if d > 0 else 2048 for d in osh]
ho = MNN.Tensor(osh, MNN.Halide_Type_Float, MNN.Tensor_DimensionType_Caffe)
ot.copyToHostTensor(ho)
mnn_h = np.asarray(ho.getNumpyData()).reshape(osh)
print('MNN fp16 elapsed:', round(t3-t2,2), 'shape', mnn_h.shape, 'finite', bool(np.isfinite(mnn_h).all()), flush=True)
a = ref_hidden.astype(np.float64).ravel(); b = mnn_h.astype(np.float64).ravel()
n=min(len(a),len(b)); a=a[:n]; b=b[:n]
cos=float(np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)+1e-9))
mae=float(np.mean(np.abs(a-b))); mx=float(np.max(np.abs(a-b)))
print('FP16-MNN vs FP32-ORT: cosine', round(cos,6), 'mae', round(mae,8), 'maxabs', round(mx,6), flush=True)
# save inputs for device reuse
emb.tofile(D + '/gb_emb_f32.raw')
pos.tofile(D + '/gb_pos_f32.raw')
kvk.tofile(D + '/gb_kvk_f32.raw')
kvv.tofile(D + '/gb_kvv_f32.raw')
cp32.tofile(D + '/gb_cp_i32.raw')
np.save(D + '/gb_ref_hidden_fp32.npy', ref_hidden)
print('INPUTS SAVED', flush=True)