import numpy as np, torch, onnxruntime as ort, MNN, time
ART = r'E:/AndroidStudioProjects/qwen3tts-mnn/artifacts/m22/onnx'
np.random.seed(7)
B,H,T,D,Cd = 1, 8, 34, 128, 2048
emb = np.random.randn(1,1,Cd).astype(np.float32)
pos = np.zeros((3,1,1), dtype=np.float32)
pos[0,0,0]=34; pos[1,0,0]=34; pos[2,0,0]=34
kvk = np.zeros((28,1,H,T,D), dtype=np.float32)
kvv = np.zeros((28,1,H,T,D), dtype=np.float32)
cp_ = np.array([34], dtype=np.int64)
sess = ort.InferenceSession(ART + '/graphb_replay_step_fp32_nonan.onnx', providers=['CPUExecutionProvider'])
onn = sess.get_inputs()[0].name
t0 = time.time()
ort_hidden, ort_layer = sess.run(None, {onn: emb, 'position_ids': pos, 'kv_k': kvk, 'kv_v': kvv, 'cache_position': cp_})
t1 = time.time()
print('ORT elapsed:', round(t1-t0,2), 'hidden', ort_hidden.shape, 'finite', bool(np.isfinite(ort_hidden).all()), flush=True)
interp = MNN.Interpreter(ART + '/graphb_replay_step_fp32_nonan.mnn')
sess2 = interp.createSession()
interp.resizeTensor(interp.getSessionInput(sess2, 'inputs_embeds'), (1,1,Cd))
interp.resizeTensor(interp.getSessionInput(sess2, 'position_ids'), (3,1,1))
interp.resizeTensor(interp.getSessionInput(sess2, 'kv_k'), (28,1,H,T,D))
interp.resizeTensor(interp.getSessionInput(sess2, 'kv_v'), (28,1,H,T,D))
interp.resizeTensor(interp.getSessionInput(sess2, 'cache_position'), (1,))
interp.resizeSession(sess2)
def feed(name, arr, dtype):
    t = interp.getSessionInput(sess2, name)
    ht = MNN.Tensor(tuple(arr.shape), dtype, arr.ravel(), MNN.Tensor_DimensionType_Caffe)
    t.copyFromHostTensor(ht)
feed('inputs_embeds', emb, MNN.Halide_Type_Float)
feed('position_ids', pos, MNN.Halide_Type_Float)
feed('kv_k', kvk, MNN.Halide_Type_Float)
feed('kv_v', kvv, MNN.Halide_Type_Float)
feed('cache_position', cp_, MNN.Halide_Type_Int)
ot = interp.getSessionOutput(sess2, 'hidden_states')
t2 = time.time()
interp.runSession(sess2)
t3 = time.time()
osh = list(ot.getShape())
ho = MNN.Tensor(osh, MNN.Halide_Type_Float, MNN.Tensor_DimensionType_Caffe)
ot.copyToHostTensor(ho)
mnn_hidden = np.asarray(ho.getNumpyData()).reshape(osh)
print('MNN elapsed:', round(t3-t2,2), 'hidden', mnn_hidden.shape, flush=True)
a = ort_hidden.astype(np.float64).ravel(); b = mnn_hidden.astype(np.float64).ravel()
n = min(len(a), len(b)); a=a[:n]; b=b[:n]
cos = float(np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)+1e-9))
mae = float(np.mean(np.abs(a-b))); mx = float(np.max(np.abs(a-b)))
print('MNN vs ORT: cosine', round(cos,6), 'mae', round(mae,8), 'maxabs', round(mx,6), flush=True)
print('M3_GRAPHB_DONE', flush=True)